steps:
  - name: ":hammer:"
    command: make setup build
    artifact_paths: 'build/*'
    plugins:
      docker-compose:
        run: builder
        config: .buildkite/docker-compose.yml

  - name: ":github: Release"
    command: .buildkite/release.sh
    branches: "master add-buildkite-ci"
    artifact_paths: 'build/*'
    plugins:
      docker-compose:
        run: builder
        config: .buildkite/docker-compose.yml
