steps:
  - name: ":hammer:"
    plugins:
      golang-build#v1.0.0:
        build: main.go
        package: github.com/lox/parfat
        targets:
         - version: 1.10.0
           goos: linux
           goarch: amd64

  - wait

  - name: ":github: Release"
    command: .buildkite/release.sh

